# Generated by Django 5.2.10 on 2026-08-15 04:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutrientDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kcal", "Kilocalorie"),
                            ("g", "Gram"),
                            ("mg", "Milligram"),
                            ("mcg", "Microgram"),
                            ("iu", "International unit"),
                        ],
                        max_length=8,
                    ),
                ),
                ("is_core", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "scope",
                    models.CharField(
                        choices=[("shared", "Shared"), ("personal", "Personal")],
                        default="personal",
                        max_length=16,
                    ),
                ),
                (
                    "origin_type",
                    models.CharField(
                        choices=[
                            ("generic", "Generic"),
                            ("branded", "Branded"),
                            ("restaurant", "Restaurant"),
                        ],
                        default="generic",
                        max_length=16,
                    ),
                ),
                ("provider_name", models.CharField(blank=True, max_length=160)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="FoodItemVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "serving_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "serving_unit",
                    models.CharField(
                        choices=[
                            ("g", "Gram"),
                            ("ml", "Milliliter"),
                            ("oz", "Ounce"),
                            ("fl_oz", "Fluid ounce"),
                            ("cup", "Cup"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                            ("item", "Item"),
                            ("serving", "Serving"),
                        ],
                        max_length=16,
                    ),
                ),
                ("serving_label", models.CharField(blank=True, max_length=120)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("community_estimate", "Community estimate"),
                            ("ai_estimate", "AI estimate"),
                            ("user_entered", "User entered"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_food_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="foods.fooditem",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="fooditem",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_food_item",
                to="foods.fooditemversion",
            ),
        ),
        migrations.CreateModel(
            name="FoodComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servings",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "child_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_by_components",
                        to="foods.fooditemversion",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="foods.fooditemversion",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="NutrientAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "food_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrient_amounts",
                        to="foods.fooditemversion",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amounts",
                        to="foods.nutrientdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["nutrient__display_order", "nutrient__name"],
            },
        ),
        migrations.CreateModel(
            name="SourceReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("provider", models.CharField(blank=True, max_length=160)),
                ("url", models.URLField(max_length=500)),
                ("accessed_on", models.DateField(blank=True, null=True)),
                (
                    "food_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="foods.fooditemversion",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="fooditemversion",
            constraint=models.UniqueConstraint(
                fields=("food_item", "version_number"),
                name="unique_food_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="fooditemversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("serving_quantity__gt", 0)),
                name="food_version_serving_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fooditemversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence_score__isnull", True),
                    models.Q(
                        ("confidence_score__gte", 0), ("confidence_score__lte", 1)
                    ),
                    _connector="OR",
                ),
                name="food_version_confidence_range",
            ),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(
                fields=["scope", "name"], name="foods_foodi_scope_4b1c7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(
                fields=["owner", "name"], name="foods_foodi_owner_i_6c05fd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fooditem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("owner__isnull", True), ("scope", "shared")),
                    models.Q(("owner__isnull", False), ("scope", "personal")),
                    _connector="OR",
                ),
                name="food_scope_matches_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodcomponent",
            constraint=models.UniqueConstraint(
                fields=("parent_version", "child_version"),
                name="unique_component_per_parent_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodcomponent",
            constraint=models.UniqueConstraint(
                fields=("parent_version", "order"),
                name="unique_component_order_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("servings__gt", 0)),
                name="food_component_servings_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent_version", models.F("child_version")), _negated=True
                ),
                name="food_component_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutrientamount",
            constraint=models.UniqueConstraint(
                fields=("food_version", "nutrient"),
                name="unique_nutrient_per_food_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutrientamount",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="nutrient_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcereference",
            constraint=models.UniqueConstraint(
                fields=("food_version", "url"),
                name="unique_source_url_per_food_version",
            ),
        ),
    ]
