# Generated by Django 5.2.10 on 2026-08-17 02:34

from decimal import Decimal

import django.core.validators
from django.db import migrations, models

NUTRIENTS = (
    ("calories", "Calories", "kcal"),
    ("protein", "Protein", "g"),
    ("carbohydrates", "Carbohydrates", "g"),
    ("fat", "Fat", "g"),
    ("fiber", "Fiber", "g"),
    ("sugar", "Sugar", "g"),
    ("sodium", "Sodium", "mg"),
    ("cholesterol", "Cholesterol", "mg"),
)
NUTRIENT_FIELDS = {key for key, _name, _unit in NUTRIENTS}


def copy_nutrient_rows_to_columns(apps, schema_editor):
    NutrientAmount = apps.get_model("foods", "NutrientAmount")
    for nutrient_amount in NutrientAmount.objects.select_related(
        "food_version", "nutrient"
    ).iterator():
        key = nutrient_amount.nutrient.key
        if key not in NUTRIENT_FIELDS:
            continue
        version = nutrient_amount.food_version
        setattr(version, key, nutrient_amount.amount)
        version.save(update_fields=[key])


def restore_nutrient_rows(apps, schema_editor):
    FoodItemVersion = apps.get_model("foods", "FoodItemVersion")
    NutrientDefinition = apps.get_model("foods", "NutrientDefinition")
    NutrientAmount = apps.get_model("foods", "NutrientAmount")
    definitions = {}
    for display_order, (key, name, unit) in enumerate(NUTRIENTS, start=1):
        definitions[key] = NutrientDefinition.objects.get_or_create(
            key=key,
            defaults={
                "name": name,
                "unit": unit,
                "is_core": True,
                "display_order": display_order * 10,
            },
        )[0]
    for version in FoodItemVersion.objects.all():
        for key in NUTRIENT_FIELDS:
            value = getattr(version, key)
            if value is None:
                continue
            NutrientAmount.objects.update_or_create(
                food_version=version,
                nutrient=definitions[key],
                defaults={"amount": value},
            )


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0002_seed_core_nutrients"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditemversion",
            name="calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="carbohydrates",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="cholesterol",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="fat",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="fiber",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="sodium",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="sugar",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.RunPython(
            copy_nutrient_rows_to_columns,
            restore_nutrient_rows,
        ),
        migrations.DeleteModel(
            name="NutrientAmount",
        ),
        migrations.DeleteModel(
            name="NutrientDefinition",
        ),
    ]
