# Generated by Django 5.2.10 on 2026-08-23 05:49

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0003_fooditemversion_calories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="shared_fingerprint",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_versions",
                to="foods.fooditemversion",
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="estimation_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="estimation_provider",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="estimation_response_id",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="serving_volume_ml",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AddField(
            model_name="fooditemversion",
            name="serving_weight_grams",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="fooditemversion",
            name="provenance",
            field=models.CharField(
                choices=[
                    ("official", "Official"),
                    ("community_estimate", "Community estimate"),
                    ("ai_estimate", "AI estimate"),
                    ("user_modified_estimate", "User-modified estimate"),
                    ("user_entered", "User entered"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="fooditem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("shared_fingerprint__isnull", True),
                    ("scope", "shared"),
                    _connector="OR",
                ),
                name="food_shared_fingerprint_scope",
            ),
        ),
    ]
