# Generated by Django 6.1 on 2026-08-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimates", "0003_alter_mealproposalrevision_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealproposalrevision",
            name="message",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
