# Generated by Django 5.2.10 on 2026-08-17 01:48

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("foods", "0002_seed_core_nutrients"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["entry_date", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MealItemSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servings",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("food_name", models.CharField(max_length=200)),
                ("provider_name", models.CharField(blank=True, max_length=160)),
                (
                    "serving_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("serving_unit", models.CharField(max_length=16)),
                ("serving_label", models.CharField(blank=True, max_length=120)),
                ("component_snapshot", models.JSONField(blank=True, default=list)),
                (
                    "food_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_item_snapshots",
                        to="foods.fooditemversion",
                    ),
                ),
                (
                    "meal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meals.mealentry",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MealNutrientSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=8)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "meal_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="meals.mealitemsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="mealentry",
            index=models.Index(
                fields=["owner", "entry_date"], name="meals_meale_owner_i_893ca2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealitemsnapshot",
            constraint=models.UniqueConstraint(
                fields=("meal_entry", "order"), name="unique_meal_item_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealitemsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("servings__gt", 0)),
                name="meal_item_servings_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealnutrientsnapshot",
            constraint=models.UniqueConstraint(
                fields=("meal_item", "key"), name="unique_nutrient_per_meal_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealnutrientsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="meal_nutrient_amount_nonnegative",
            ),
        ),
    ]
