# Generated by Django 5.2.10 on 2026-08-17 02:34

from decimal import Decimal

import django.core.validators
from django.db import migrations, models

NUTRIENTS = (
    ("calories", "Calories", "kcal"),
    ("protein", "Protein", "g"),
    ("carbohydrates", "Carbohydrates", "g"),
    ("fat", "Fat", "g"),
    ("fiber", "Fiber", "g"),
    ("sugar", "Sugar", "g"),
    ("sodium", "Sodium", "mg"),
    ("cholesterol", "Cholesterol", "mg"),
)


def copy_nutrient_rows_to_columns(apps, schema_editor):
    MealNutrientSnapshot = apps.get_model("meals", "MealNutrientSnapshot")
    for nutrient_snapshot in MealNutrientSnapshot.objects.select_related(
        "meal_item"
    ).iterator():
        if nutrient_snapshot.key not in {key for key, _name, _unit in NUTRIENTS}:
            continue
        meal_item = nutrient_snapshot.meal_item
        setattr(meal_item, nutrient_snapshot.key, nutrient_snapshot.amount)
        meal_item.save(update_fields=[nutrient_snapshot.key])


def restore_nutrient_rows(apps, schema_editor):
    MealItemSnapshot = apps.get_model("meals", "MealItemSnapshot")
    MealNutrientSnapshot = apps.get_model("meals", "MealNutrientSnapshot")
    MealNutrientSnapshot.objects.bulk_create(
        [
            MealNutrientSnapshot(
                meal_item=meal_item,
                key=key,
                name=name,
                unit=unit,
                amount=value,
                display_order=display_order,
            )
            for meal_item in MealItemSnapshot.objects.all()
            for display_order, (key, name, unit) in enumerate(NUTRIENTS)
            if (value := getattr(meal_item, key)) is not None
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0003_fooditemversion_calories_and_more"),
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitemsnapshot",
            name="calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="mealitemsnapshot",
            name="carbohydrates",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="mealitemsnapshot",
            name="cholesterol",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="mealitemsnapshot",
            name="fat",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="mealitemsnapshot",
            name="fiber",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="mealitemsnapshot",
            name="protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="mealitemsnapshot",
            name="sodium",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="mealitemsnapshot",
            name="sugar",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.RunPython(
            copy_nutrient_rows_to_columns,
            restore_nutrient_rows,
        ),
        migrations.DeleteModel(
            name="MealNutrientSnapshot",
        ),
    ]
